# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.22

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/egely1337/cubobezier

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/egely1337/cubobezier

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all:
	$(CMAKE_COMMAND) -E cmake_progress_start /home/egely1337/cubobezier/CMakeFiles /home/egely1337/cubobezier//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/egely1337/cubobezier/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

#=============================================================================
# Target rules for targets named Cubobezier

# Build rule for target.
Cubobezier:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Cubobezier
.PHONY : Cubobezier

# fast build rule for target.
Cubobezier/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Cubobezier.dir/build.make CMakeFiles/Cubobezier.dir/build
.PHONY : Cubobezier/fast

src/Camera/Camera.o: src/Camera/Camera.cpp.o
.PHONY : src/Camera/Camera.o

# target to build an object file
src/Camera/Camera.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Cubobezier.dir/build.make CMakeFiles/Cubobezier.dir/src/Camera/Camera.cpp.o
.PHONY : src/Camera/Camera.cpp.o

src/Camera/Camera.i: src/Camera/Camera.cpp.i
.PHONY : src/Camera/Camera.i

# target to preprocess a source file
src/Camera/Camera.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Cubobezier.dir/build.make CMakeFiles/Cubobezier.dir/src/Camera/Camera.cpp.i
.PHONY : src/Camera/Camera.cpp.i

src/Camera/Camera.s: src/Camera/Camera.cpp.s
.PHONY : src/Camera/Camera.s

# target to generate assembly for a file
src/Camera/Camera.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Cubobezier.dir/build.make CMakeFiles/Cubobezier.dir/src/Camera/Camera.cpp.s
.PHONY : src/Camera/Camera.cpp.s

src/File/File.o: src/File/File.cpp.o
.PHONY : src/File/File.o

# target to build an object file
src/File/File.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Cubobezier.dir/build.make CMakeFiles/Cubobezier.dir/src/File/File.cpp.o
.PHONY : src/File/File.cpp.o

src/File/File.i: src/File/File.cpp.i
.PHONY : src/File/File.i

# target to preprocess a source file
src/File/File.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Cubobezier.dir/build.make CMakeFiles/Cubobezier.dir/src/File/File.cpp.i
.PHONY : src/File/File.cpp.i

src/File/File.s: src/File/File.cpp.s
.PHONY : src/File/File.s

# target to generate assembly for a file
src/File/File.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Cubobezier.dir/build.make CMakeFiles/Cubobezier.dir/src/File/File.cpp.s
.PHONY : src/File/File.cpp.s

src/ObjLoader/objloader.o: src/ObjLoader/objloader.cpp.o
.PHONY : src/ObjLoader/objloader.o

# target to build an object file
src/ObjLoader/objloader.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Cubobezier.dir/build.make CMakeFiles/Cubobezier.dir/src/ObjLoader/objloader.cpp.o
.PHONY : src/ObjLoader/objloader.cpp.o

src/ObjLoader/objloader.i: src/ObjLoader/objloader.cpp.i
.PHONY : src/ObjLoader/objloader.i

# target to preprocess a source file
src/ObjLoader/objloader.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Cubobezier.dir/build.make CMakeFiles/Cubobezier.dir/src/ObjLoader/objloader.cpp.i
.PHONY : src/ObjLoader/objloader.cpp.i

src/ObjLoader/objloader.s: src/ObjLoader/objloader.cpp.s
.PHONY : src/ObjLoader/objloader.s

# target to generate assembly for a file
src/ObjLoader/objloader.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Cubobezier.dir/build.make CMakeFiles/Cubobezier.dir/src/ObjLoader/objloader.cpp.s
.PHONY : src/ObjLoader/objloader.cpp.s

src/Object/Object.o: src/Object/Object.cpp.o
.PHONY : src/Object/Object.o

# target to build an object file
src/Object/Object.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Cubobezier.dir/build.make CMakeFiles/Cubobezier.dir/src/Object/Object.cpp.o
.PHONY : src/Object/Object.cpp.o

src/Object/Object.i: src/Object/Object.cpp.i
.PHONY : src/Object/Object.i

# target to preprocess a source file
src/Object/Object.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Cubobezier.dir/build.make CMakeFiles/Cubobezier.dir/src/Object/Object.cpp.i
.PHONY : src/Object/Object.cpp.i

src/Object/Object.s: src/Object/Object.cpp.s
.PHONY : src/Object/Object.s

# target to generate assembly for a file
src/Object/Object.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Cubobezier.dir/build.make CMakeFiles/Cubobezier.dir/src/Object/Object.cpp.s
.PHONY : src/Object/Object.cpp.s

src/Shader/Shader.o: src/Shader/Shader.cpp.o
.PHONY : src/Shader/Shader.o

# target to build an object file
src/Shader/Shader.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Cubobezier.dir/build.make CMakeFiles/Cubobezier.dir/src/Shader/Shader.cpp.o
.PHONY : src/Shader/Shader.cpp.o

src/Shader/Shader.i: src/Shader/Shader.cpp.i
.PHONY : src/Shader/Shader.i

# target to preprocess a source file
src/Shader/Shader.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Cubobezier.dir/build.make CMakeFiles/Cubobezier.dir/src/Shader/Shader.cpp.i
.PHONY : src/Shader/Shader.cpp.i

src/Shader/Shader.s: src/Shader/Shader.cpp.s
.PHONY : src/Shader/Shader.s

# target to generate assembly for a file
src/Shader/Shader.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Cubobezier.dir/build.make CMakeFiles/Cubobezier.dir/src/Shader/Shader.cpp.s
.PHONY : src/Shader/Shader.cpp.s

src/Window/Window.o: src/Window/Window.cpp.o
.PHONY : src/Window/Window.o

# target to build an object file
src/Window/Window.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Cubobezier.dir/build.make CMakeFiles/Cubobezier.dir/src/Window/Window.cpp.o
.PHONY : src/Window/Window.cpp.o

src/Window/Window.i: src/Window/Window.cpp.i
.PHONY : src/Window/Window.i

# target to preprocess a source file
src/Window/Window.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Cubobezier.dir/build.make CMakeFiles/Cubobezier.dir/src/Window/Window.cpp.i
.PHONY : src/Window/Window.cpp.i

src/Window/Window.s: src/Window/Window.cpp.s
.PHONY : src/Window/Window.s

# target to generate assembly for a file
src/Window/Window.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Cubobezier.dir/build.make CMakeFiles/Cubobezier.dir/src/Window/Window.cpp.s
.PHONY : src/Window/Window.cpp.s

src/imgui/imgui.o: src/imgui/imgui.cpp.o
.PHONY : src/imgui/imgui.o

# target to build an object file
src/imgui/imgui.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Cubobezier.dir/build.make CMakeFiles/Cubobezier.dir/src/imgui/imgui.cpp.o
.PHONY : src/imgui/imgui.cpp.o

src/imgui/imgui.i: src/imgui/imgui.cpp.i
.PHONY : src/imgui/imgui.i

# target to preprocess a source file
src/imgui/imgui.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Cubobezier.dir/build.make CMakeFiles/Cubobezier.dir/src/imgui/imgui.cpp.i
.PHONY : src/imgui/imgui.cpp.i

src/imgui/imgui.s: src/imgui/imgui.cpp.s
.PHONY : src/imgui/imgui.s

# target to generate assembly for a file
src/imgui/imgui.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Cubobezier.dir/build.make CMakeFiles/Cubobezier.dir/src/imgui/imgui.cpp.s
.PHONY : src/imgui/imgui.cpp.s

src/imgui/imgui_demo.o: src/imgui/imgui_demo.cpp.o
.PHONY : src/imgui/imgui_demo.o

# target to build an object file
src/imgui/imgui_demo.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Cubobezier.dir/build.make CMakeFiles/Cubobezier.dir/src/imgui/imgui_demo.cpp.o
.PHONY : src/imgui/imgui_demo.cpp.o

src/imgui/imgui_demo.i: src/imgui/imgui_demo.cpp.i
.PHONY : src/imgui/imgui_demo.i

# target to preprocess a source file
src/imgui/imgui_demo.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Cubobezier.dir/build.make CMakeFiles/Cubobezier.dir/src/imgui/imgui_demo.cpp.i
.PHONY : src/imgui/imgui_demo.cpp.i

src/imgui/imgui_demo.s: src/imgui/imgui_demo.cpp.s
.PHONY : src/imgui/imgui_demo.s

# target to generate assembly for a file
src/imgui/imgui_demo.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Cubobezier.dir/build.make CMakeFiles/Cubobezier.dir/src/imgui/imgui_demo.cpp.s
.PHONY : src/imgui/imgui_demo.cpp.s

src/imgui/imgui_draw.o: src/imgui/imgui_draw.cpp.o
.PHONY : src/imgui/imgui_draw.o

# target to build an object file
src/imgui/imgui_draw.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Cubobezier.dir/build.make CMakeFiles/Cubobezier.dir/src/imgui/imgui_draw.cpp.o
.PHONY : src/imgui/imgui_draw.cpp.o

src/imgui/imgui_draw.i: src/imgui/imgui_draw.cpp.i
.PHONY : src/imgui/imgui_draw.i

# target to preprocess a source file
src/imgui/imgui_draw.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Cubobezier.dir/build.make CMakeFiles/Cubobezier.dir/src/imgui/imgui_draw.cpp.i
.PHONY : src/imgui/imgui_draw.cpp.i

src/imgui/imgui_draw.s: src/imgui/imgui_draw.cpp.s
.PHONY : src/imgui/imgui_draw.s

# target to generate assembly for a file
src/imgui/imgui_draw.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Cubobezier.dir/build.make CMakeFiles/Cubobezier.dir/src/imgui/imgui_draw.cpp.s
.PHONY : src/imgui/imgui_draw.cpp.s

src/imgui/imgui_impl_glfw.o: src/imgui/imgui_impl_glfw.cpp.o
.PHONY : src/imgui/imgui_impl_glfw.o

# target to build an object file
src/imgui/imgui_impl_glfw.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Cubobezier.dir/build.make CMakeFiles/Cubobezier.dir/src/imgui/imgui_impl_glfw.cpp.o
.PHONY : src/imgui/imgui_impl_glfw.cpp.o

src/imgui/imgui_impl_glfw.i: src/imgui/imgui_impl_glfw.cpp.i
.PHONY : src/imgui/imgui_impl_glfw.i

# target to preprocess a source file
src/imgui/imgui_impl_glfw.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Cubobezier.dir/build.make CMakeFiles/Cubobezier.dir/src/imgui/imgui_impl_glfw.cpp.i
.PHONY : src/imgui/imgui_impl_glfw.cpp.i

src/imgui/imgui_impl_glfw.s: src/imgui/imgui_impl_glfw.cpp.s
.PHONY : src/imgui/imgui_impl_glfw.s

# target to generate assembly for a file
src/imgui/imgui_impl_glfw.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Cubobezier.dir/build.make CMakeFiles/Cubobezier.dir/src/imgui/imgui_impl_glfw.cpp.s
.PHONY : src/imgui/imgui_impl_glfw.cpp.s

src/imgui/imgui_impl_opengl3.o: src/imgui/imgui_impl_opengl3.cpp.o
.PHONY : src/imgui/imgui_impl_opengl3.o

# target to build an object file
src/imgui/imgui_impl_opengl3.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Cubobezier.dir/build.make CMakeFiles/Cubobezier.dir/src/imgui/imgui_impl_opengl3.cpp.o
.PHONY : src/imgui/imgui_impl_opengl3.cpp.o

src/imgui/imgui_impl_opengl3.i: src/imgui/imgui_impl_opengl3.cpp.i
.PHONY : src/imgui/imgui_impl_opengl3.i

# target to preprocess a source file
src/imgui/imgui_impl_opengl3.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Cubobezier.dir/build.make CMakeFiles/Cubobezier.dir/src/imgui/imgui_impl_opengl3.cpp.i
.PHONY : src/imgui/imgui_impl_opengl3.cpp.i

src/imgui/imgui_impl_opengl3.s: src/imgui/imgui_impl_opengl3.cpp.s
.PHONY : src/imgui/imgui_impl_opengl3.s

# target to generate assembly for a file
src/imgui/imgui_impl_opengl3.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Cubobezier.dir/build.make CMakeFiles/Cubobezier.dir/src/imgui/imgui_impl_opengl3.cpp.s
.PHONY : src/imgui/imgui_impl_opengl3.cpp.s

src/imgui/imgui_tables.o: src/imgui/imgui_tables.cpp.o
.PHONY : src/imgui/imgui_tables.o

# target to build an object file
src/imgui/imgui_tables.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Cubobezier.dir/build.make CMakeFiles/Cubobezier.dir/src/imgui/imgui_tables.cpp.o
.PHONY : src/imgui/imgui_tables.cpp.o

src/imgui/imgui_tables.i: src/imgui/imgui_tables.cpp.i
.PHONY : src/imgui/imgui_tables.i

# target to preprocess a source file
src/imgui/imgui_tables.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Cubobezier.dir/build.make CMakeFiles/Cubobezier.dir/src/imgui/imgui_tables.cpp.i
.PHONY : src/imgui/imgui_tables.cpp.i

src/imgui/imgui_tables.s: src/imgui/imgui_tables.cpp.s
.PHONY : src/imgui/imgui_tables.s

# target to generate assembly for a file
src/imgui/imgui_tables.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Cubobezier.dir/build.make CMakeFiles/Cubobezier.dir/src/imgui/imgui_tables.cpp.s
.PHONY : src/imgui/imgui_tables.cpp.s

src/imgui/imgui_widgets.o: src/imgui/imgui_widgets.cpp.o
.PHONY : src/imgui/imgui_widgets.o

# target to build an object file
src/imgui/imgui_widgets.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Cubobezier.dir/build.make CMakeFiles/Cubobezier.dir/src/imgui/imgui_widgets.cpp.o
.PHONY : src/imgui/imgui_widgets.cpp.o

src/imgui/imgui_widgets.i: src/imgui/imgui_widgets.cpp.i
.PHONY : src/imgui/imgui_widgets.i

# target to preprocess a source file
src/imgui/imgui_widgets.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Cubobezier.dir/build.make CMakeFiles/Cubobezier.dir/src/imgui/imgui_widgets.cpp.i
.PHONY : src/imgui/imgui_widgets.cpp.i

src/imgui/imgui_widgets.s: src/imgui/imgui_widgets.cpp.s
.PHONY : src/imgui/imgui_widgets.s

# target to generate assembly for a file
src/imgui/imgui_widgets.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Cubobezier.dir/build.make CMakeFiles/Cubobezier.dir/src/imgui/imgui_widgets.cpp.s
.PHONY : src/imgui/imgui_widgets.cpp.s

src/main.o: src/main.cpp.o
.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Cubobezier.dir/build.make CMakeFiles/Cubobezier.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Cubobezier.dir/build.make CMakeFiles/Cubobezier.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Cubobezier.dir/build.make CMakeFiles/Cubobezier.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... Cubobezier"
	@echo "... src/Camera/Camera.o"
	@echo "... src/Camera/Camera.i"
	@echo "... src/Camera/Camera.s"
	@echo "... src/File/File.o"
	@echo "... src/File/File.i"
	@echo "... src/File/File.s"
	@echo "... src/ObjLoader/objloader.o"
	@echo "... src/ObjLoader/objloader.i"
	@echo "... src/ObjLoader/objloader.s"
	@echo "... src/Object/Object.o"
	@echo "... src/Object/Object.i"
	@echo "... src/Object/Object.s"
	@echo "... src/Shader/Shader.o"
	@echo "... src/Shader/Shader.i"
	@echo "... src/Shader/Shader.s"
	@echo "... src/Window/Window.o"
	@echo "... src/Window/Window.i"
	@echo "... src/Window/Window.s"
	@echo "... src/imgui/imgui.o"
	@echo "... src/imgui/imgui.i"
	@echo "... src/imgui/imgui.s"
	@echo "... src/imgui/imgui_demo.o"
	@echo "... src/imgui/imgui_demo.i"
	@echo "... src/imgui/imgui_demo.s"
	@echo "... src/imgui/imgui_draw.o"
	@echo "... src/imgui/imgui_draw.i"
	@echo "... src/imgui/imgui_draw.s"
	@echo "... src/imgui/imgui_impl_glfw.o"
	@echo "... src/imgui/imgui_impl_glfw.i"
	@echo "... src/imgui/imgui_impl_glfw.s"
	@echo "... src/imgui/imgui_impl_opengl3.o"
	@echo "... src/imgui/imgui_impl_opengl3.i"
	@echo "... src/imgui/imgui_impl_opengl3.s"
	@echo "... src/imgui/imgui_tables.o"
	@echo "... src/imgui/imgui_tables.i"
	@echo "... src/imgui/imgui_tables.s"
	@echo "... src/imgui/imgui_widgets.o"
	@echo "... src/imgui/imgui_widgets.i"
	@echo "... src/imgui/imgui_widgets.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

